-- http://www.techonthenet.com/oracle/tablespaces/drop_tablespace.php
DROP TABLESPACE BAP_DATA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE BAP_INDX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
