-- http://www.techonthenet.com/oracle/tablespaces/drop_tablespace.php

DECLARE
     TableSpaceExistsExcep     EXCEPTION;
     PRAGMA EXCEPTION_INIT(TableSpaceExistsExcep,-00959);
BEGIN
     EXECUTE IMMEDIATE 'DROP TABLESPACE BAP_DATA INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS';
     EXECUTE IMMEDIATE 'DROP TABLESPACE BAP_INDX INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS';
EXCEPTION
     WHEN TablespaceExistsExcep THEN
          DBMS_OUTPUT.PUT_LINE('Creating tablespaces failed....');
          NULL;
END;
/
